### ISSUE TITLE
Fix application properties

### ISSUE THREAD

**Issue by HerbMat** [dorm-social-room-manager/dsrm-backend#67]
Add to readme description of
```
dsrm:
  auth:
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
```
Move those properties from applicaiton-local.yml to application.yml
